"""Claw Bridge adapter for CrewAI.

Maps:
- CrewAI Agent roles         -> Adaptoid worker definitions
- CrewAI Task descriptions   -> Adaptoid wave tasks
- CrewAI Crew process        -> orchestrator workflow mode
"""
from pathlib import Path
from typing import Any, Dict

from .base import FrameworkAdapter


class CrewAIAdapter(FrameworkAdapter):
    """Import/export between CrewAI crews and Adaptoid OS plans."""

    name = "crewai"

    def import_plan(self, artifact: Any) -> Dict:
        if isinstance(artifact, dict):
            crew = artifact
        else:
            crew = self._parse_crew_file(Path(artifact))

        waves = []
        for task in crew.get("tasks", []):
            waves.append({
                "id": f"wave-{task['name']}",
                "name": task.get("description", "")[:60],
                "tasks": [{"id": task["name"], "agent": task.get("agent", ""), "prompt": task.get("description", "")}],
                "gate": {"type": "auto"},
            })

        return {
            "archetype": "crewai-import",
            "tier": "T1",
            "framework": "crewai",
            "agents": crew.get("agents", []),
            "waves": waves,
        }

    def export_plan(self, plan: Dict) -> str:
        """Emit a minimal CrewAI crew script."""
        lines = [
            "from crewai import Agent, Task, Crew",
            "",
        ]
        for agent in plan.get("agents", []):
            name = agent["name"]
            role = agent.get("role", name)
            goal = agent.get("goal", "")
            lines += [
                f"{name.lower()}_agent = Agent(",
                f'    role="{role}",',
                f'    goal="{goal}",',
                '    backstory="Generated by Adaptoid OS",',
                '    verbose=True,',
                ")",
                "",
            ]
        for i, wave in enumerate(plan.get("waves", [])):
            for task in wave.get("tasks", []):
                tid = task["id"]
                agent = task.get("agent", "agent")
                desc = task.get("prompt", "")
                lines += [
                    f"task_{i} = Task(",
                    f'    description="{desc}",',
                    f'    agent={agent.lower()}_agent,',
                    ")",
                    "",
                ]
        lines += [
            "crew = Crew(",
            "    agents=[agent for agent in locals().values() if isinstance(agent, Agent)],",
            "    tasks=[task for task in locals().values() if isinstance(task, Task)],",
            '    process="sequential",',
            ")",
            "result = crew.kickoff()",
            "print(result)",
        ]
        return "\n".join(lines)

    def import_skill(self, artifact: Any) -> Dict:
        if isinstance(artifact, str):
            return {"name": Path(artifact).stem, "source": "crewai"}
        return {"name": artifact.get("name", "unknown"), "source": "crewai"}

    def export_skill(self, skill_doc: Dict) -> str:
        name = skill_doc.get("name", "tool")
        desc = skill_doc.get("description", "")
        return f"""from crewai.tools import BaseTool

class {name.title()}Tool(BaseTool):
    name: str = "{name}"
    description: str = "{desc}"

    def _run(self, query: str) -> str:
        return "result"
"""

    @staticmethod
    def _parse_crew_file(path: Path) -> Dict:
        """Naive parser for demonstration; production use should import the module."""
        text = path.read_text()
        return {
            "agents": [{"name": "researcher", "role": "researcher", "goal": "find facts"}],
            "tasks": [{"name": "research_task", "agent": "researcher", "description": "Research the topic."}],
        }
